const DAY='2026-08-24';
const PREV_DAY='2026-08-23';
const jobs=window.JOBS||[],oldJobs=window.OLDJOBS||[];
function norm(u){try{let x=new URL(u);if(x.hostname.includes('indeed.com')){let jk=x.searchParams.get('jk');return jk?'indeed:'+jk:x.origin+x.pathname}return x.origin+x.pathname.replace(/\/$/,'')}catch(e){return u}}
function pk(j){return 'jobstatus:'+norm(j.apply)} function legacy(i){return localStorage.getItem('job-'+PREV_DAY+'-'+i)||''}
function migrate(){oldJobs.forEach(j=>{let v=legacy(j.id);if(v&&!localStorage.getItem(pk(j)))localStorage.setItem(pk(j),v)})} function st(j){return localStorage.getItem(pk(j))||''}
function esc(x){return String(x??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))} function attr(x){return esc(x).replace(/`/g,'&#96;')}
function commonAnswers(j){return[['Current location','Glasgow, United Kingdom. Open to UK-wide relocation and remote/hybrid roles.'],['Right to work','I have the right to work in the UK on a Graduate visa valid until February 2028. I do not require sponsorship now; I would require sponsorship after my current visa expires.'],['Commercial experience','8+ years of commercial software-development experience.'],['Relevant experience','My strongest relevant experience for this role is: '+j.skills+'.'],['Why this role','This role is a strong match for my background in scalable SaaS, backend/API engineering and full-stack delivery. '+j.why],['Leadership','I have led a five-developer engineering team, contributed to architecture decisions, performed code reviews and supported engineering best practices.'],['Availability','Available to interview with reasonable notice and open to discussing the employer’s preferred start date.'],['Salary','Open to the advertised range and happy to discuss based on the overall role and package.']]}
async function cp(t,b){let ok=false;try{if(navigator.clipboard&&window.isSecureContext){await navigator.clipboard.writeText(t);ok=true}}catch(e){}if(!ok){try{let a=document.createElement('textarea');a.value=t;a.style.position='fixed';a.style.opacity='0';document.body.appendChild(a);a.focus();a.select();a.setSelectionRange(0,99999);ok=document.execCommand('copy');document.body.removeChild(a)}catch(e){}}let z=b.innerText;b.innerText=ok?'COPIED':'SELECT';if(!ok)window.prompt('Copy this answer:',t);setTimeout(()=>b.innerText=z,1100)}
function tog(i){let e=document.getElementById('a'+i);if(e)e.style.display=e.style.display==='block'?'none':'block'} function setS(j,v){if(!j)return;let key=pk(j);if(v){localStorage.setItem(key,v);localStorage.setItem(key+':at',new Date().toISOString())}else{localStorage.removeItem(key);localStorage.removeItem(key+':at')}render();setTimeout(nextUnfinished,80)} function nextUnfinished(){let e=document.querySelector('#cards .card:not(.donec)');if(e)e.scrollIntoView({behavior:'smooth',block:'start'})} function portal(j){return j.source||((j.apply||'').includes('indeed.com')?'Indeed':'Direct')}
function render(){let c=document.getElementById('cards');c.innerHTML='';let d=jobs.filter(j=>st(j)==='done').length,h=jobs.filter(j=>st(j)==='help').length;document.getElementById('fill').style.width=(jobs.length?d/jobs.length*100:0)+'%';document.getElementById('count').innerText=d+' / '+jobs.length+' completed · '+h+' need help';jobs.forEach((j,n)=>{let state=st(j),aa=commonAnswers(j).map(([q,v])=>`<div class=q><b>${esc(q)}:</b><div class=av>${esc(v)}</div><button class=cp data-copy="${attr(v)}" onclick="cp(this.dataset.copy,this)">COPY</button></div>`).join('');c.innerHTML+=`<div class="card ${state==='help'?'help':''} ${state==='done'?'donec':''}"><div class=top><b>#${n+1} · ${n<12?'APPLY FIRST':'GOOD MATCH'}</b><span class=match>${esc(j.match)}</span></div><h2>${esc(j.title)}</h2><b>${esc(j.company)}</b><div class=badges><span class=portal>${esc(portal(j))}</span><span class=posted>${esc(j.posted||'Posting date not shown')}</span></div><div class=meta>${esc(j.meta)}</div><div class=why>${esc(j.why)}</div><div class=ats><b>ATS focus:</b> ${esc(j.skills)}</div><button class="btn cv" onclick="cv(${j.id},false)">GET MASTER-BASED CV</button><a class="btn ap" target=_blank rel="noopener noreferrer" href="${attr(j.apply)}">APPLY NOW · ${esc(portal(j))}</a><button class="btn ans" onclick="tog(${j.id})">ANSWERS / COPY</button><div class=abox id=a${j.id}>${aa}</div><div class=row><button class=d onclick='setS(jobs.find(x=>x.id===${j.id}),"done")'>DONE</button><button class=h onclick='setS(jobs.find(x=>x.id===${j.id}),"help")'>NEED HELP</button><button class=r onclick='setS(jobs.find(x=>x.id===${j.id}),"")'>RESET</button></div></div>`});pending()}
function pending(){let p=document.getElementById('pending'),a=[...oldJobs.filter(j=>st(j)==='help').map(j=>({...j,old:true})),...jobs.filter(j=>st(j)==='help')];let seen=new Set();a=a.filter(j=>{let k=norm(j.apply);if(seen.has(k))return false;seen.add(k);return true});p.innerHTML=a.length?a.map(j=>`<div class="card help"><h2>${esc(j.title)}</h2><b>${esc(j.company)}</b><div class=meta>${esc(j.meta||'')}</div><button class="btn cv" onclick='cv(${j.id},${j.old?'true':'false'})'>GET MASTER-BASED CV</button><a class="btn ap" target=_blank rel="noopener noreferrer" href="${attr(j.apply)}">CONTINUE APPLICATION · ${esc(portal(j))}</a></div>`).join(''):'<div class=card>No pending jobs.</div>'} function tab(x){document.getElementById('cards').style.display=x?'none':'block';document.getElementById('pending').style.display=x?'block':'none';document.getElementById('t1').className=x?'':'on';document.getElementById('t2').className=x?'on':'';if(x)pending()}
function cv(i,isOld){let list=isOld?oldJobs:jobs,j=list.find(x=>x.id===i);if(!j)return;let{jsPDF}=window.jspdf,d=new jsPDF({unit:'mm',format:'a4'}),y=13,L=13,W=184;function ensure(n=12){if(y+n>283){d.addPage();y=13}} function line(t,z=8.3,b=0,g=2){ensure(10);d.setFont('helvetica',b?'bold':'normal');d.setFontSize(z);let a=d.splitTextToSize(t,W);d.text(a,L,y);y+=a.length*(z<9?3.45:3.8)+g} function hd(t){ensure(12);y+=1;d.setFont('helvetica','bold');d.setFontSize(10.2);d.text(t,L,y);y+=4;d.setLineWidth(.25);d.line(L,y-2.4,L+W,y-2.4)}
// MASTER CV IS THE BASE. Job data only changes title/profile emphasis and adds truthful ATS terms.
d.setFont('helvetica','bold');d.setFontSize(17);d.text('Waleed Mazhar',L,y);y+=6;d.setFontSize(11);d.text(j.title||'Full-Stack Developer',L,y);y+=5;d.setFont('helvetica','normal');d.setFontSize(8.5);d.text('Glasgow, United Kingdom | +44 7404536622 | waleed.mazhar02@gmail.com | LinkedIn | GitHub',L,y);y+=7;
hd('Personal Statement');line('Full-Stack Developer with 8+ years of experience delivering scalable, enterprise-grade web applications across SaaS, healthcare, advertising, and analytics domains. Skilled in Laravel, Node.js, Angular, and TypeScript, with strong expertise in building cloud-native systems on AWS, Docker, and CI/CD pipelines. Proven ability to design and optimise microservices architectures, secure RESTful APIs, and high-performance systems that improve scalability, efficiency, and reliability. Experienced in full lifecycle development, from system design to deployment, with a strong focus on clean architecture, maintainable code, and responsive user interfaces. For this role, relevant ATS alignment includes: '+j.skills+'.');
hd('Education');line('MSc in Artificial Intelligence | University of the West of Scotland, UK | 2024 – 2025\nBSc in Software Engineering | University of Engineering & Technology, Pakistan | 2012 – 2016');
hd('Skills & Expertise');line('Full-Stack Development: Laravel (PHP) | Node.js | Angular | TypeScript | JavaScript (ES6+) | HTML5 | CSS3 | RESTful APIs | GraphQL | WebSockets (Socket.io) | Microservices Architecture');line('Backend Development: PHP (Laravel Framework) | Node.js | API Development & Integration | JWT Authentication | Role-Based Access Control (RBAC) | Performance Optimisation | Caching Strategies | Backend Refactoring');line('Frontend Development: Angular | React | TypeScript | JavaScript | Responsive UI Development | Component-Based Architecture | Single Page Applications (SPA) | HTML5 | CSS3 | UI/UX Optimisation | Mobile-First Design');line('Cloud, DevOps & Databases: AWS (Lambda | S3 | EC2 | API Gateway) | Docker | Kubernetes | CI/CD (GitHub Actions) | MySQL | PostgreSQL | MongoDB | MariaDB | Database Design | Query Optimisation');line('Software Engineering & AI Integration: Git | GitHub | JIRA | Agile/Scrum | Postman | System Design | Microservices Architecture | Python | TensorFlow | Scikit-learn | OpenAI API | AI/ML Integration | Clean Code Principles');line('Job-specific ATS terminology (truthful overlap): '+j.skills+'.',8.1,1);
hd('Work Experience');line('Senior Full-Stack Developer | Histone Solutions, Pakistan | Jan 2021 – Sep 2024',9.1,1);line('• Optimised supply chain operations using Laravel, PHP, MySQL, and AWS, delivering a 60% reduction in processing time through end-to-end system improvements.\n• Spearheaded development of a SaaS analytics platform for 10,000+ Amazon sellers using Laravel, PHP, Angular, TypeScript, AWS, Docker, and MySQL, enabling scalable and data-driven decision-making.\n• Engineered and optimised RESTful APIs with PHP, Laravel, and MySQL, significantly enhancing real-time data processing efficiency and system responsiveness.\n• Re-architected and refactored 100+ Angular and TypeScript components, strengthening frontend scalability, maintainability, and overall application performance.\n• Implemented AWS Lambda-based serverless workflows and CI/CD pipelines using AWS and Docker, accelerating deployment cycles while improving automation and system reliability.\n• Delivered robust full-stack solutions across Laravel, PHP, Angular, TypeScript, AWS, Docker, and MySQL, ensuring high-performance, scalable, and production-ready systems.',8.1);
line('Full-Stack Engineer | Softisans, Pakistan | Sep 2019 – Dec 2020',9.1,1);line('• Engineered a scalable cloud-based healthcare SaaS platform using Laravel, Angular, TypeScript and REST APIs, delivering secure and efficient digital healthcare services at scale.\n• Developed production full-stack functionality across Laravel backend services and Angular/TypeScript user interfaces.\n• Built and integrated REST APIs, real-time WebSocket functionality and payment workflows, and supported cloud deployment.',8.1);
line('Full-Stack Developer | Nested Logics, Pakistan | Aug 2016 – Aug 2019',9.1,1);line('• Developed production web platforms using Laravel, Angular, Node.js and MySQL, including an advertising monetisation platform serving 25,000+ websites.\n• Architected and built 50+ modular, reusable Angular and Node.js components, improving code reuse and maintainability.\n• Integrated 40+ RESTful APIs across Laravel and Node.js services and developed analytics/reporting functionality.',8.1);
d.save('Waleed_Mazhar_'+(j.company||'Company').replace(/[^a-z0-9]+/gi,'_')+'_ATS_CV.pdf')}
migrate();render();